- name: Check if router exists
  shell: openstack router show {{ shared_router }}
  ignore_errors: yes
  register: router_show

- name: Add admin network for tenant access
  shell: openstack router add subnet {{ shared_router }} {{ project }}_subnet
  when: router_show.rc == 0
